github.com:
    users:
        Khetreiqcer:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Khetreiqcer
